#!/usr/bin/env bash
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MARKER="agent-kit:managed"
ALL_TARGETS="cursor codex claude gemini windsurf cline roo"

usage() {
  cat <<EOF
Usage: ./uninstall.sh [--target <list>] [--components <list>] [--project <path>] [--dry-run]

  --target <list>      Comma-separated from: cursor,codex,claude,gemini,windsurf,cline,roo,all
                       (default: all)
  --components <list>  Comma-separated from: rules,skills,all  (default: all)
  --project <path>     Uninstall from project level under <path> (default: global home dirs)
  --dry-run            Print actions without making changes

Only removes symlinks that point back into this repo, and cursor .mdc files
generated by agent-kit (marked with "$MARKER"). Other real files are left untouched.
EOF
}

TARGETS="$ALL_TARGETS"
COMPONENTS="rules skills"
PROJECT=""
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target) TARGETS="${2//,/ }"; shift 2 ;;
    --components) COMPONENTS="${2//,/ }"; shift 2 ;;
    --project) PROJECT="$(cd "$2" && pwd)"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown arg: $1"; usage; exit 1 ;;
  esac
done
case " $TARGETS " in *" all "*) TARGETS="$ALL_TARGETS" ;; esac
case " $COMPONENTS " in *" all "*) COMPONENTS="rules skills" ;; esac

dest_for() {  # dest_for <target>
  if [[ -n "$PROJECT" ]]; then
    case "$1" in
      cursor)   echo "$PROJECT/.cursor/rules/behavior.mdc" ;;
      codex)    echo "$PROJECT/AGENTS.md" ;;
      claude)   echo "$PROJECT/CLAUDE.md" ;;
      gemini)   echo "$PROJECT/GEMINI.md" ;;
      windsurf) echo "$PROJECT/.windsurf/rules/behavior.md" ;;
      cline)    echo "$PROJECT/.clinerules/behavior.md" ;;
      roo)      echo "$PROJECT/.roo/rules/behavior.md" ;;
    esac
  else
    case "$1" in
      cursor)   echo "$HOME/.cursor/rules/behavior.mdc" ;;
      codex)    echo "$HOME/.codex/AGENTS.md" ;;
      claude)   echo "$HOME/.claude/CLAUDE.md" ;;
      gemini)   echo "$HOME/.gemini/GEMINI.md" ;;
      windsurf) echo "$HOME/.codeium/windsurf/memories/global_rules.md" ;;
      cline)    echo "$HOME/Documents/Cline/Rules/behavior.md" ;;
      roo)      echo "$HOME/.roo/rules/behavior.md" ;;
    esac
  fi
}

skills_dir() {  # skills_dir <target>; empty output = no skills for this target
  if [[ -n "$PROJECT" ]]; then
    case "$1" in
      cursor)   echo "$PROJECT/.cursor/skills" ;;
      claude)   echo "$PROJECT/.claude/skills" ;;
      codex)    echo "$PROJECT/.agents/skills" ;;
      gemini)   echo "$PROJECT/.gemini/skills" ;;
      windsurf) echo "$PROJECT/.windsurf/skills" ;;
      cline)    echo "$PROJECT/.cline/skills" ;;
      *)        echo "" ;;
    esac
  else
    case "$1" in
      cursor)   echo "$HOME/.cursor/skills" ;;
      claude)   echo "$HOME/.claude/skills" ;;
      codex)    echo "$HOME/.agents/skills" ;;
      gemini)   echo "$HOME/.gemini/skills" ;;
      windsurf) echo "$HOME/.codeium/windsurf/skills" ;;
      cline)    echo "$HOME/.cline/skills" ;;
      *)        echo "" ;;
    esac
  fi
}

remove() {  # remove <dst>
  if [[ $DRY_RUN -eq 1 ]]; then echo "[dry-run] would remove: $1"; else rm "$1"; echo "removed: $1"; fi
}

unlink_if_ours() {  # unlink_if_ours <dst>
  local dst="$1"
  [[ -L "$dst" ]] || return 0
  local tgt; tgt="$(readlink "$dst")"
  case "$tgt" in
    "$REPO"/*) remove "$dst" ;;
    *) echo "skip (not ours): $dst -> $tgt" ;;
  esac
}

remove_cursor() {  # remove_cursor <dst>
  local dst="$1"
  if [[ -L "$dst" ]]; then unlink_if_ours "$dst"; return; fi
  [[ -e "$dst" ]] || return 0
  if grep -q "$MARKER" "$dst" 2>/dev/null; then remove "$dst"; else echo "skip (not ours): $dst"; fi
}

for t in $TARGETS; do
  dst="$(dest_for "$t")"
  sd="$(skills_dir "$t")"
  if [[ -z "$dst" && -z "$sd" ]]; then echo "unknown target: $t (skipped)"; continue; fi

  if [[ " $COMPONENTS " == *" rules "* && -n "$dst" ]]; then
    if [[ "$t" == "cursor" ]]; then
      remove_cursor "$dst"
    else
      unlink_if_ours "$dst"
    fi
  fi

  if [[ " $COMPONENTS " == *" skills "* && -n "$sd" ]]; then
    for d in "$REPO"/skills/*/; do
      [[ -d "$d" ]] && unlink_if_ours "$sd/$(basename "$d")"
    done
  fi
done

echo "Done. Targets: $TARGETS | components: ${COMPONENTS// /,}${PROJECT:+ (project: $PROJECT)}"
